### ISSUE TITLE
Err 400 : redirect_uri_mismatch

### ISSUE THREAD

**Issue by Jeremy3191** [polius/RetroX#1]
Hi Guys, 

I am having a problem at the end of the process described here : https://www.retrox.app/setup
Here the result I get. Is there something I did wrong ?

<img width="625" alt="Capture d’écran 2024-04-29 à 17 24 05" src="https://github.com/polius/RetroX/assets/160591925/bfd0da5f-f7b6-4a61-8fe4-7cd1bc189e4e">

Thx for your answers

**Comment by polius** [comment]
Hi Jeremy,

Thanks for reaching out! This error occurs when the **Authorized redirect URIs** section does not contain the following URL.

```
https://www.retrox.app/callback
```

![step3 9](https://github.com/polius/RetroX/assets/691095/83e5c330-ee8e-4fd3-bc4d-c8c1c4997db4)

Could you please check which value you have added?

RetroX Setup Page:
[https://www.retrox.app/setup](https://www.retrox.app/setup)

**Comment by Jeremy3191** [comment]
Hi Pollius, 

I missed this part. It works now, thank you for your help !

**Comment by Jeremy3191** [comment]
Hi Pollius,

I missed this part. It works now, thank you for your help !
